tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
tap "microsoft/git"
tap "puma/puma"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# New way to see and navigate directory trees
brew "broot"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Programmatically minimize files to isolate features of interest
brew "delta"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Load/unload environment variables based on $PWD
brew "direnv"
# Modern replacement for 'ls'
brew "exa"
# Command-line tool to interact with exercism.io
brew "exercism"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Small git utilities
brew "git-extras"
# Process manager for Procfile-based applications
brew "hivemind"
# <hr />, for your terminal window
brew "hr"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Curl statistics made simple
brew "httpstat"
# Website copier/offline browser
brew "httrack"
# Command-line benchmarking tool
brew "hyperfine"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Curses-based tool for viewing and analyzing log files
brew "lnav"
# Security and system auditing tool to harden systems
brew "lynis"
# Keep your Mac's application settings in sync
brew "mackup"
# Securely transfers data between computers
brew "magic-wormhole"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# Open source relational database management system
brew "mysql@5.7"
# Network grep
brew "ngrep"
# Process manager for Procfile-based applications and tmux
brew "overmind"
# CLI for Postgres with auto-completion and syntax highlighting
brew "pgcli"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Object-relational database system
brew "postgresql"
# Wrapper to colorize and simplify ping's output
brew "prettyping"
# Monitor data's progress through a pipe
brew "pv"
# Tools for and transforming and inspecting PDF files
brew "qpdf"
# Rsync for cloud storage
brew "rclone"
# Persistent key-value database, with built-in net interface
brew "redis"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Wrapper around ripgrep that adds multiple rich file types
brew "ripgrep-all"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Cross-shell prompt for astronauts
brew "starship"
# Simplified and community-driven man pages
brew "tldr"
# Program that allows you to count code, quickly
brew "tokei"
# Process YAML documents from the CLI
brew "yq"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Next-generation plugin manager for zsh
brew "zplug"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# Mac App Store command-line interface
brew "mas-cli/tap/mas"
# A tool to manage rack apps in development with puma
brew "puma/puma/puma-dev"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line helper for the 1Password password manager
cask "1password-cli"
# File and photo tweaking tool
cask "a-better-finder-attributes"
# Renamer for files, music and photos
cask "a-better-finder-rename"
# Application launcher and productivity software
cask "alfred"
# Redis desktop manager
cask "another-redis-desktop-manager"
# Application uninstaller
cask "appcleaner"
# Multi-cloud backup application
cask "arq"
cask "background-music"
# Menu bar icon organizer
cask "bartender"
# Text, code, and markup editor
cask "bbedit"
# Cross platform SQL editor and database management app
cask "beekeeper-studio"
# Tool to customize input devices and automate computer systems
cask "bettertouchtool"
# Bookmarks manager
cask "bookmacster"
# E-books management software
cask "calibre"
# Use your phone as a high-quality webcam with image tuning controls
cask "camo-studio"
# Contacts manager
cask "cardhop"
# Open links in any browser
cask "choosy"
# Automated testing of webapps for Google Chrome
cask "chromedriver"
# Downloads videos and audio from websites
cask "clipgrab"
# Disk space visualizer
cask "daisydisk"
# API documentation browser and code snippet manager
cask "dash"
# Utility to enhance the Open and Save dialogs in applications
cask "default-folder-x"
# Tool to compare and synchronize files and folders
cask "deltawalker"
# Application window manager focusing on simplicity
cask "divvy"
# App to build and share containerized applications and microservices
cask "docker"
# Fork of the DOSBox project
cask "dosbox-x"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Finds duplicate files in a computer system
cask "dupeguru"
# Control your Elgato Key Lights
cask "elgato-control-center"
# Assign keys, and then decorate and label them
cask "elgato-stream-deck"
# Network drive and browser for cloud storage
cask "expandrive"
# VPN client for secure internet access and private browsing
cask "expressvpn"
# Free, open-source SQL client
cask "falcon-sql-client"
# Calendar software
cask "fantastical"
# Web browser
cask "firefox"
# Tool to turn a website into a desktop app
cask "fluid"
cask "font-anonymice-nerd-font"
cask "font-bitstream-vera-sans-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-public-sans"
cask "font-sauce-code-pro-nerd-font"
# YouTube player focusing on privacy
cask "freetube"
# Move playlists, tracks, and albums between music platforms
cask "freeyourmusic"
cask "git-credential-manager-core"
# Web browser
cask "google-chrome"
# Tools to protect your files
cask "gpg-suite-no-mail"
# GraphQL IDE for better development workflows
cask "graphql-playground"
# Desktop automation application
cask "hammerspoon"
# Automated organization
cask "hazel"
# Free and open-source media player
cask "iina"
# Tool to optimize images to a smaller size
cask "imageoptim"
# HTTP and GraphQL Client
cask "insomnia"
# System monitoring app
cask "istat-menus"
# Spot and merge differences in text and image files or folders
cask "kaleidoscope"
# Keyboard customizer
cask "karabiner-elements"
# Tool to prevent the system from going into sleep mode
cask "keepingyouawake"
# File archiver
cask "keka"
# Automation software
cask "keyboard-maestro"
# Open-source keystroke visualizer
cask "keycastr"
# Finds, learns and remembers keyboard shortcuts
cask "keycue"
# Animated screen capture application
cask "licecap"
# Host-based application firewall
cask "little-snitch"
# Ergonomic Assistant to prevent health problems
cask "macbreakz"
# Open-source Markdown editor
cask "macdown"
# Email tracker, read receipt and spy pixel blocker plugin for Apple Mail
cask "mailtrackerblocker"
# Extensible two-pane file manager
cask "marta"
# Monitors and reports any microphone and camera activity
cask "micro-snitch"
# Silence embarrassing notifications while screensharing
cask "muzzle"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Scheduling application focusing on organization
cask "omnifocus"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# File manager
cask "path-finder"
# HTTP client that helps testing and describing APIs
cask "paw"
# Integrated reading environment
cask "polar-bookshelf"
# Flexible software sketchbook and a language for learning how to code
cask "processing"
cask "qbserve"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# QuickLook generator for Markdown files
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Emoji picker optimized for blind people
cask "rocket"
# Block your own access to distracting websites
cask "selfcontrol"
# Instant messaging application focusing on security
cask "signal"
cask "sonos-s1-controller"
# Sound and audio controller
cask "soundsource"
# Graphical client for Git version control
cask "sourcetree"
# Music streaming service
cask "spotify"
# Video game digital distribution service
cask "steam"
# Break time reminder app
cask "stretchly"
# Backup, recovery and cloning software
cask "superduper"
# Application for inspecting installer packages
cask "suspicious-package"
# Replacement for RCDefaultApps, written in Swift
cask "swiftdefaultappsprefpane"
# Unpacks archive files
cask "the-unarchiver"
# Open-source BitTorrent client
cask "transmission"
# Open-source code editor
cask "visual-studio-code"
# Media direct transfer tool for Apple devices
cask "waltr"
# Comic reader
cask "yacreader"
# Flash tool for ZSA keyboards
cask "zsa-wally"
# Desktop client for the Zulip team chat platform
cask "zulip"
mas "Be Focused Pro", id: 961632517
mas "Deliveries", id: 924726344
mas "Focus Matrix", id: 1087284172
mas "Monosnap", id: 540348655
mas "myTuner Radio", id: 881415018
mas "Pixelmator", id: 407963104
mas "Pocket", id: 568494494
mas "Reeder", id: 1449412482
mas "Save to Pocket", id: 1477385213
mas "SomaFM", id: 449155338
mas "Spark", id: 1176895641
mas "StopTheMadness", id: 1376402589
