tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "hpedrorodrigues/tools"
tap "mas-cli/tap"
tap "microsoft/git"
tap "puma/puma"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# New way to see and navigate directory trees
brew "broot"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Load/unload environment variables based on $PWD
brew "direnv"
# Modern replacement for 'ls'
brew "exa"
# Command-line tool to interact with exercism.io
brew "exercism"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Small git utilities
brew "git-extras"
# Process manager for Procfile-based applications
brew "hivemind"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Curl statistics made simple
brew "httpstat"
# Command-line benchmarking tool
brew "hyperfine"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Security and system auditing tool to harden systems
brew "lynis"
# Keep your Mac's application settings in sync
brew "mackup"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# CLI for Postgres with auto-completion and syntax highlighting
brew "pgcli"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Object-relational database system
brew "postgresql@14"
# Wrapper to colorize and simplify ping's output
brew "prettyping"
# Monitor data's progress through a pipe
# Tools for and transforming and inspecting PDF files
brew "qpdf"
# Rsync for cloud storage
brew "rclone"
# Persistent key-value database, with built-in net interface
brew "redis"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Wrapper around ripgrep that adds multiple rich file types
brew "ripgrep-all"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Cross-shell prompt for astronauts
brew "starship"
# Easiest, most secure way to use WireGuard and 2FA
brew "tailscale"
# Simplified and community-driven man pages
brew "tldr"
# Program that allows you to count code, quickly
brew "tokei"
# Internet file retriever
brew "wget"
# Process YAML documents from the CLI
brew "yq"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Next-generation plugin manager for zsh
brew "zplug"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# Mac App Store command-line interface
brew "mas-cli/tap/mas"
# A tool to manage rack apps in development with puma
brew "puma/puma/puma-dev"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line helper for the 1Password password manager
cask "1password-cli"
# File and photo tweaking tool
cask "a-better-finder-attributes"
# Renamer for files, music and photos
cask "a-better-finder-rename"
# Application launcher and productivity software
cask "alfred"
# Redis desktop manager
cask "another-redis-desktop-manager"
# Application uninstaller
cask "appcleaner"
# Multi-cloud backup application
cask "arq"
# Menu bar icon organizer
cask "bartender"
# Text, code, and markup editor
cask "bbedit"
# Cross platform SQL editor and database management app
cask "beekeeper-studio"
# Tool to customize input devices and automate computer systems
cask "bettertouchtool"
# Bookmarks manager
cask "bookmacster"
# E-books management software
cask "calibre"
# Use your phone as a high-quality webcam with image tuning controls
cask "camo-studio"
# Contacts manager
cask "cardhop"
# Open links in any browser
cask "choosy"
# Automated testing of webapps for Google Chrome
cask "chromedriver"
# Downloads videos and audio from websites
cask "clipgrab"
# Disk space visualizer
cask "daisydisk"
# API documentation browser and code snippet manager
cask "dash"
# Utility to enhance the Open and Save dialogs in applications
cask "default-folder-x"
# Tool to compare and synchronize files and folders
cask "deltawalker"
# Voice and text chat software
cask "discord"
# Application window manager focusing on simplicity
cask "divvy"
# Finds duplicate files in a computer system
cask "dupeguru"
# Control your Elgato Key Lights
cask "elgato-control-center"
# Assign keys, and then decorate and label them
cask "elgato-stream-deck"
# Network drive and browser for cloud storage
cask "expandrive"
# Calendar software
cask "fantastical"
# Web browser
cask "firefox"
cask "font-anonymice-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-bitstream-vera-sans-mono-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
cask "font-inconsolata-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-meslo-lg-nerd-font"
cask "font-public-sans"
cask "font-sauce-code-pro-nerd-font"
cask "git-credential-manager-core"
# Web browser
cask "google-chrome"
# Tools to protect your files
cask "gpg-suite-no-mail"
# Desktop automation application
cask "hammerspoon"
# Automated organization
cask "hazel"
# Workaround for 'dockutil' on macOS >= 12.3, See https://github.com/kcrawford/dockutil/issues/127
cask 'hpedrorodrigues/tools/dockutil'
# Free and open-source media player
cask "iina"
# System monitoring app
cask "istat-menus"
# JetBrains tools manager
cask "jetbrains-toolbox"
# Note taking and to-do application with synchronization capabilities
cask "joplin"
# Keyboard customizer
cask "karabiner-elements"
# Tool to prevent the system from going into sleep mode
cask "keepingyouawake"
# File archiver
cask "keka"
# Automation software
cask "keyboard-maestro"
# Open-source keystroke visualizer
cask "keycastr"
# Finds, learns and remembers keyboard shortcuts
cask "keycue"
# Animated screen capture application
cask "licecap"
# Ergonomic Assistant to prevent health problems
cask "macbreakz"
# Open-source Markdown editor
cask "macdown"
# Email tracker, read receipt and spy pixel blocker plugin for Apple Mail
cask "mailtrackerblocker"
# Extensible two-pane file manager
cask "marta"
# Monitors and reports any microphone and camera activity
cask "micro-snitch"
# Silence embarrassing notifications while screensharing
cask "muzzle"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Scheduling application focusing on organization
cask "omnifocus"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# File manager
cask "path-finder"
# HTTP client that helps testing and describing APIs
cask "paw"
# VPN client focusing on security
cask "protonvpn"
# Automatic time tracker
cask "qbserve"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# QuickLook generator for Markdown files
cask "qlmarkdown"
cask "qlprettypatch"
# QuickLook plugin for plaintext files without an extension
cask "qlstephen"
# QuickLook generator for video files
cask "qlvideo"
# QuickLook plugin for CSV files
cask "quicklook-csv"
# QuickLook plugin for JSON files
cask "quicklook-json"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Emoji picker optimized for blind people
cask "rocket"
# Block your own access to distracting websites
cask "selfcontrol"
# Team communication and collaboration software
cask "slack"
# Sound and audio controller
cask "soundsource"
# Graphical client for Git version control
cask "sourcetree"
# Break time reminder app
cask "stretchly"
# Git client
cask "sublime-merge"
# Text editor for code, markup and prose
cask "sublime-text"
# Backup, recovery and cloning software
cask "superduper"
# Application for inspecting installer packages
cask "suspicious-package"
# Replacement for RCDefaultApps, written in Swift
cask "swiftdefaultappsprefpane"
# Unpacks archive files
cask "the-unarchiver"
# Managing Pull Requests and Issues For GitHub & GitHub Enterprise
cask "trailer"
# Flash tool for ZSA keyboards
cask "zsa-wally"
# Desktop client for the Zulip team chat platform
cask "zulip"
mas "1Password for Safari", id: 1569813296
mas "Be Focused Pro", id: 961632517
mas "Deliveries", id: 290986013
mas "Focus Matrix", id: 1087284172
mas "Horo", id: 1437226581
mas "Microsoft Remote Desktop", id: 1295203466
mas "Monosnap", id: 540348655
mas "myTuner Radio", id: 881415018
mas "Pixelmator", id: 407963104
mas "Pocket", id: 568494494
mas "Reeder", id: 1449412482
mas "Save to Pocket", id: 1477385213
mas "SomaFM", id: 449155338
mas "Spark", id: 1176895641
mas "StopTheMadness", id: 1376402589
mas "Things", id: 904280696
mas "Wayback Machine", id: 1472432422
